language: go
go:
  - 1.3
install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/stretchr/testify
  - go get github.com/robertkrimen/gxc/gxc
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/sysward/sysward-agent

script:
  - cd $GOPATH/src/github.com/sysward/sysward-agent
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
