language: go
go:
  - 1.3
  - 1.4
install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/stretchr/testify
  - go get github.com/robertkrimen/gxc/gxc
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/bradfitz/goimports

script:
  - cp -r $HOME/gopath/src/github.com/sysward/sysward-agent $HOME/gopath/src/sysward_agent
  - ./cover.sh
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN
